
name: Release Build

on:
  release:
    types:
      - released
    branches:
      - "main"

jobs:
  call-workflow:
    uses: PepperDash/workflow-templates/.github/workflows/essentialsplugins-builds.yml@main
    secrets: inherit
    with: 
      branch: "main"
      default-branch: "main"


